# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a3uac-LdaYlqr5Qy6CinfiFC0AjpJuEq
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
import pandas as pd
import io
# --- 0. CONFIGURAÇÃO DA PÁGINA ---
st.set_page_config(layout="wide", page_title="Explorador de Espectros Estelares")

# --- 1. FUNÇÕES E DADOS COMUNS (DEFINIDOS UMA VEZ PARA TODO O APP) ---
# Todas as funções e dicionários que você definiu no seu notebook.

def planck(wavelength_nm, T_kelvin):
    h = 6.626e-34; c = 3.0e8; k = 1.38e-23
    wav_m = wavelength_nm * 1e-9
    intensity = (2*h*c**2) / (wav_m**5 * (np.exp((h*c)/(wav_m*k*T_kelvin)) - 1))
    return np.nan_to_num(intensity)

def calcular_temp_por_pico(pico_nm):
    b = 2.898e-3
    pico_m = pico_nm * 1e-9
    if pico_m == 0: return 0
    return b / pico_m

def calcular_pico_wien(T_kelvin):
    b = 2.898e-3
    lambda_max_m = b / T_kelvin
    return lambda_max_m * 1e9

def get_classe_espectral(temp):
    if temp >= 30000: return "O"
    elif temp >= 10000 and temp < 30000: return "B"
    elif temp >= 7500 and temp < 10000: return "A"
    elif temp >= 6000 and temp < 7500: return "F"
    elif temp >= 5200 and temp < 6000: return "G"
    elif temp >= 3700 and temp < 5200: return "K"
    elif temp >= 2400 and temp < 3700: return "M"
    else: return "M"

def mostrar_tutorial_csv():
    """
    Exibe um st.expander com o tutorial de como abrir arquivos CSV.
    """
    with st.expander("Clique aqui para ver como abrir o arquivo .csv no Google Sheets ou Excel"):
        st.markdown("""
        O arquivo `.csv` é um formato de texto simples para tabelas, compatível com a maioria dos programas de planilha. Veja como importá-lo:

        ### 📈 Google Sheets (Planilhas Google)
        1. Abra o Google Sheets em seu navegador: [sheets.google.com](https://sheets.google.com).
        2. No menu superior, vá em **Arquivo** > **Importar**.
        3. Na janela que abrir, clique na aba **Upload** e selecione o arquivo `.csv` que você baixou.
        4. O Google geralmente detecta as configurações automaticamente. Apenas confirme se o **Tipo de separador** está como "Vírgula (,)" e clique em **Importar dados**.

        ### 📊 Microsoft Excel
        1. Abra o Microsoft Excel e crie uma **Pasta de trabalho em branco**.
        2. Vá para a aba **Dados** no menu superior.
        3. Na seção "Obter e Transformar Dados", clique em **Do Texto/CSV**.
        4. Selecione o arquivo `.csv` que você baixou.
        5. Uma janela de pré-visualização irá abrir. O Excel deve detectar automaticamente que o **Delimitador** é "Vírgula". Se estiver correto, clique no botão **Carregar**.
        """)
def gerar_relatorio_universal(lista_de_itens):
    """
    Gera um relatório em formato CSV a partir de uma lista de itens.
    Cada item é um dicionário que pode ser do tipo 'tabela' ou 'qa'.
    """
    output = io.StringIO()

    for item in lista_de_itens:
        # Adiciona um espaço antes de cada novo item, exceto o primeiro
        if lista_de_itens.index(item) > 0:
            output.write('\n\n')

        # Se o item for uma tabela (DataFrame)
        if item['tipo'] == 'tabela':
            output.write(f"### {item['titulo']} ###\n") # Adiciona um título para a tabela
            item['df'].to_csv(output, index=False)

        # Se o item for um par de Pergunta e Resposta
        elif item['tipo'] == 'qa':
            # Cria um mini-dataframe para formatar a P&R em duas colunas
            qa_df = pd.DataFrame({
                "Item": [item['pergunta']],
                "Resposta": [item['resposta'] if item['resposta'] else "Não respondido."]
            })
            qa_df.to_csv(output, index=False)

    return output.getvalue()

LINHAS_ATLAS = {
    "Si IV":  {"linhas": [140.0, 155.0], "cor": "peachpuff"}, "He II":  {"linhas": [468.58, 656.00], "cor": "purple"},
    "Si III": {"linhas": [455.26, 456.78, 457.47], "cor": "darksalmon"}, "He I":   {"linhas": [388.84, 447.15, 587.56], "cor": "blue"},
    "Mg II":  {"linhas": [448.11], "cor": "dodgerblue"}, "Si II":  {"linhas": [634.71, 637.14], "cor": "deepskyblue"},
    "H":      {"linhas": [388.90, 410.17, 434.05, 486.13, 656.28], "cor": "cyan"}, "Ca II":  {"linhas": [393.40, 396.90], "cor": "green"},
    "Fe II":  {"linhas": [492.4, 501.8, 516.9], "cor": "limegreen"}, "Fe I":   {"linhas": [438.79, 526.95, 532.80], "cor": "gold"},
    "Ca I":   {"linhas": [422.67, 646.26, 649.38], "cor": "orange"}, "TiO":    {"linhas": [668.9, 709.0], "cor": "red"}
}

PARAMETROS_INTENSIDADE_AJUSTADOS = {
    "Si IV": (40000, 2500, 0.30), "He II": (35000, 4500, 0.60), "He I": (22000, 6000, 0.75),
    "Si III": (17000, 2500, 0.35), "Si II": (13500, 3000, 0.50), "Mg II": (9500, 2000, 0.40),
    "H": (10000, 3500, 1.00), "Fe II": (7000, 1800, 0.50), "Ca II": (5200, 1600, 1.00),
    "Fe I": (4500, 2000, 0.75), "Ca I": (3900, 1700, 0.85), "TiO": (3200, 1000, 1.0)
}
LINHAS_QUENTES = ["He II", "He I", "Si IV", "Si III", "Si II", "Mg II"]
LINHAS_FRIAS   = ["Fe I", "Ca I", "TiO"]

# --- TÍTULO PRINCIPAL DO APP ---
st.title("🔭 Espectroscopia com Luz Visível")

st.markdown("""
Bem-vindo ao Explorador de Espectros Estelares!
Esta ferramenta interativa foi projetada para ajudar a entender como os astrônomos usam a luz das estrelas para determinar suas propriedades, como temperatura e composição química.
Use as abas abaixo para progredir passo a passo, desde a radiação de corpo negro até a identificação de elementos químicos pelo espectro de luz visível.
""")

# --- ESTRUTURA DE ABAS ---
tab1, tab2, tab3, tab4, tab5, tab6, tab7 = st.tabs([
    "Etapa 1: Radiação Ideal",
    "Etapa 2: Atlas Espectral",
    "Etapa 3: Espectro com Absorção",
    "Etapa 4: Investigação",
    "Etapa 5: Linha de referência",
    "Etapa 6: O espectro real: O trabalho do astrofísico(a)",
    "Tutorial e Créditos"
])
# 3. Função para converter o DataFrame para CSV
@st.cache_data
def convert_df_to_csv(df):
  return df.to_csv(index=False).encode('utf-8')

# --- CÓDIGO DA ETAPA 1 (TRADUÇÃO LITERAL DA CÉLULA 1) ---
with tab1:
    st.header("Radiação ideal de estrelas")

    pico_slider = st.slider("Pico de Emissão (λ_max):", 50, 3000, 500, 5, key="pico_e1")
    c1, c2 = st.columns(2)
    with c1:
        x_min_slider = st.slider("Zoom Mín (nm):", 0, 2000, 0, 10, key="zoom_min_e1")
    with c2:
        x_max_slider = st.slider("Zoom Máx (nm):", 500, 4000, 1500, 10, key="zoom_max_e1")

    # Lógica de plotagem da Etapa 1
    temperatura = calcular_temp_por_pico(pico_slider)
    classe = get_classe_espectral(temperatura)
    wavelengths = np.linspace(x_min_slider, x_max_slider, 2000)
    fluxo_total = planck(np.linspace(1, 4000, 4000), temperatura)
    fluxo_continuo = planck(wavelengths, temperatura)
    max_real = np.max(fluxo_total)
    if max_real == 0: max_real = 1
    fluxo_norm = fluxo_continuo / max_real
    fig, ax = plt.subplots(figsize=(14, 7))
    ax.set_facecolor('#1e1e1e')
    cmap = LinearSegmentedColormap.from_list('vis', [(0.0,(0.29,0,0.51)), (0.17,(0,0,1)), (0.33,(0,1,1)), (0.50,(0,1,0)), (0.67,(1,1,0)), (0.83,(1,0.5,0)), (1.0,(1,0,0))])
    ax.imshow(np.vstack((wavelengths, wavelengths)), aspect='auto', cmap=cmap, extent=[400, 700, -0.05, 1.1])
    ax.plot(wavelengths, fluxo_norm, color='white', linewidth=2)
    if x_min_slider <= pico_slider <= x_max_slider:
        ax.axvline(x=pico_slider, color='gold', linestyle='--', linewidth=2, label=f'Pico de Emissão (λ_max): {pico_slider:.1f} nm')
    ax.set_title(f"Espectro para λ_max = {pico_slider} nm (Classe {classe})", color='white', fontsize=16)
    ax.set_xlabel('Comprimento de Onda (nm)', color='white')
    ax.set_ylabel('Intensidade Relativa (Pico Real = 1)', color='white')
    ax.set_xlim(x_min_slider, x_max_slider); ax.set_ylim(-0.05, 1.1)
    ax.legend(loc='upper right')
    fig.set_facecolor('black')
    ax.grid(True, linestyle='--', alpha=0.5, color='gray')
    ax.tick_params(colors='white', which='both')
    ax_top = ax.twiny()
    ax_top.set_xlim(ax.get_xlim())
    tick_positions = [calcular_pico_wien(t) for t in [30000, 10000, 7500, 6000, 5200, 3700]]
    tick_labels = ['O', 'B', 'A', 'F', 'G', 'K']
    ax_top.set_xticks(tick_positions)
    ax_top.set_xticklabels(tick_labels, fontsize=12)
    ax_top.set_xlabel('Classe Espectral', color='white', fontsize=12, labelpad=10)
    pos_m = calcular_pico_wien(2400)
    ax_top.text(pos_m, 1.05, 'M', color='white', ha='center', va='center', transform=ax_top.get_xaxis_transform())
    ax_top.grid(False)
    ax_top.tick_params(axis='x', which='both', colors='white')
    st.pyplot(fig)

  # --- SEÇÃO DE ATIVIDADE (VERSÃO CORRIGIDA) ---
    st.divider()
    st.header("Atividade Prática: Usando a Lei de Wien")
    st.markdown("Use o simulador acima para encontrar o comprimento de onda de pico ($\lambda_{max}$) de diferentes classes de estrelas e anote na tabela abaixo para calcular suas temperaturas.")
    st.info("""
    **Instruções:**
    1. Use o simulador acima para encontrar o $\lambda_{max}$ para cada classe espectral.
    2. **Observe o gráfico:** Para cada classe, qual é a cor predominante que a estrela emite na faixa visível (entre 400 e 700 nm)? Onde a curva de intensidade é mais alta nessa faixa? Anote a cor (ex: "Azul", "Branco-azulado","Branco", "Amarelo", "Laranja", "Vermelho").
    3. Preencha a tabela abaixo. A temperatura será calculada automaticamente.
    4. Ao final, responda à pergunta de conclusão.
    """)
    with st.expander("Clique para ver a explicação e um Exemplo de Cálculo"):
        st.subheader("A Fórmula da Lei de Wien")
        st.latex(r''' T = \frac{b}{\lambda_{\text{max}}} ''')
        st.markdown(r"""- $T$ = Temperatura (em Kelvin), $\lambda_{\text{max}}$ = Comprimento de onda do pico (em **metros**), $b$ = $2.898 \times 10^{-3} \text{ m}\cdot\text{K}$.
- **Lembre-se de converter:** $1 \text{ nm} = 1 \times 10^{-9} \text{ m}$.
- **Exemplo:** Para o Sol (Classe G), $\lambda_{max} \approx 500 \text{ nm}$. $T = \frac{2.898 \times 10^{-3}}{500 \times 10^{-9}} \approx 5796 \text{ K}$.
        """)
    
    if 'df_wien' not in st.session_state:
        dados_iniciais = {
            "Classe Espectral": ["G (Exemplo)", "", "", ""],
            "λ_max (nm)": [500.0, None, None, None],
            "Temperatura (K)": [5796.0, None, None, None],
            "Cor Predominante Observada": ["Branco", "", "", ""]
        }
        st.session_state.df_wien = pd.DataFrame(dados_iniciais)

    # Agora a tabela é criada com a garantia de que o session_state existe
    df_editado_e1 = st.data_editor(
        st.session_state.df_wien,
        num_rows="dynamic",
        hide_index=True,
        key="editor_etapa1"
    )
    st.session_state.df_wien = df_editado_e1

    # O resto do código do gabarito e download continua daqui para baixo, sem alterações...
    observacoes_feitas = (st.session_state.df_wien['λ_max (nm)'].dropna().astype(str).str.strip() != '').sum()
    st.divider()
    if observacoes_feitas >= 6:
        st.subheader("Gabarito da atividade")
        st.success("Parabéns por completar a atividade! Confira seus cálculos na tabela abaixo.")

        # Prepara o DataFrame do gabarito
        df_aluno = st.session_state.df_wien.dropna(subset=['λ_max (nm)']).copy()
        df_aluno['Temperatura Correta (K)'] = df_aluno['λ_max (nm)'].apply(
            lambda x: round(calcular_temp_por_pico(pd.to_numeric(x, errors='coerce')), 1) if pd.to_numeric(x, errors='coerce') > 0 else None
        )

        # Renomeia colunas para clareza no gabarito
        df_gabarito = df_aluno.rename(columns={
            "λ_max (nm)": "λ_max (nm) Anotado",
            "Temperatura (K)": "Sua Temperatura (K) Anotada"
        })

        # Exibe o gabarito
        st.dataframe(
            df_gabarito[["λ_max (nm) Anotado", "Sua Temperatura (K) Anotada", "Temperatura Correta (K)"]],
            hide_index=True,
            use_container_width=True
        )
    else:
        st.info(f"""
        Você fez **{observacoes_feitas}** de **6** observações necessárias.

        Continue calculando e preenchendo a tabela para revelar o gabarito e conferir seus resultados!
        """)

    csv_para_download = convert_df_to_csv(st.session_state.df_wien)
    st.download_button(label="📥 Baixar tabela em CSV", data=csv_para_download, file_name='minhas_temperaturas_wien.csv', mime='text/csv')

    # MUDANÇA: Adicionada a caixa de pergunta e resposta para a conclusão
    st.divider()
    st.subheader("Pergunta de Conclusão")
    st.markdown("""
    Baseado nos dados que você coletou na tabela, qual é a relação entre a **temperatura** de uma estrela e a **cor** que ela emite? Sua conclusão é diferente do que o senso comum nos diz sobre as cores azul e vermelho para frio e quente?
    """)
    conclusao_aluno = st.text_area("Escreva sua conclusão aqui:", height=150)

    # --- SEÇÃO DE DOWNLOAD REATORADA ---
    st.divider()
    st.header("Salvar seu Trabalho da Etapa 1")

    # 1. Crie a "lista de tarefas" para o relatório da Etapa 1
    itens_relatorio_e1 = [
        {
            'tipo': 'tabela',
            'titulo': 'Tabela - Lei de Wien e Cor das Estrelas',
            'df': st.session_state.df_wien
        },
        {
            'tipo': 'qa',
            'pergunta': 'Conclusão: Qual a relação entre a temperatura de uma estrela e a sua cor?',
            'resposta': conclusao_aluno
        }
    ]

    # 2. Gere o relatório chamando a função universal
    relatorio_csv_e1 = gerar_relatorio_universal(itens_relatorio_e1)

    # 3. Crie o botão de download único
    st.download_button(
        label="📥 Baixar Relatório Completo da Etapa 1 (CSV)",
        data=relatorio_csv_e1.encode('utf-8'),
        file_name='relatorio_completo_etapa1.csv',
        mime='text/csv'
    )

    mostrar_tutorial_csv()
# --- CÓDIGO DA ETAPA 2 (TRADUÇÃO LITERAL DA CÉLULA 2) ---
# --- CONTEÚDO DA ETAPA 2 ---
with tab2:
    st.header("Atlas Espectral de alguns átomos e um composto")
    st.markdown("Este é um atlas de referência que mostra as 'impressões digitais' (linhas de absorção) dos principais elementos encontrados em estrelas.")

    # 1. Preparação da Figura
    fig_atlas, axs_atlas = plt.subplots(len(LINHAS_ATLAS), 1, figsize=(12, 20), sharex=False)
    fig_atlas.set_facecolor('black')
    fig_atlas.suptitle('Atlas Espectral de Referência para Classificação Estelar', fontsize=20, y=0.99, color='white')

    # 2. Loop para criar cada subplot do atlas
    wavelengths_atlas = np.linspace(380, 800, 4000)
    num_elementos = len(LINHAS_ATLAS)

    for i, (nome, dados) in enumerate(LINHAS_ATLAS.items()):
        fluxo = np.ones_like(wavelengths_atlas)
        largura = 1.0 if nome != "TiO" else 8.0

        for linha_pos in dados["linhas"]:
            # Só desenha a gaussiana se a linha estiver na faixa visível do atlas
            if 380 <= linha_pos <= 800:
                gaussiana = 0.8 * np.exp(-((wavelengths_atlas - linha_pos)**2) / (2 * largura**2))
                fluxo -= gaussiana

        ax = axs_atlas[i]
        ax.set_facecolor('#1e1e1e')
        ax.plot(wavelengths_atlas, np.clip(fluxo, 0, 1), color=dados["cor"], lw=2)
        ax.set_title(f'Elemento: {nome}', loc='left', color="white")
        ax.set_yticks([]); ax.set_ylabel('Absorção', color="white")
        ax.grid(True, linestyle='--', alpha=0.3)
        ax.set_xlim(wavelengths_atlas.min(), wavelengths_atlas.max())
        ax.tick_params(colors='white', which='both')

        # Lógica para formatar o eixo X exatamente como no seu notebook
        ax.set_xticks(np.arange(400, wavelengths_atlas.max() + 1, 50))
        ax.tick_params(axis='x', colors='white', labelcolor='white')

        if i < num_elementos - 1:
            ax.set_xlabel('')
            ax.tick_params(labelbottom=True)
        else:
            ax.set_xlabel('Comprimento de Onda (nm)', color="white")

    plt.tight_layout(rect=[0, 0, 1, 0.98])

    # 3. Exibição da figura no Streamlit
    st.pyplot(fig_atlas)

    # --- TABELA INTERATIVA ---
    st.subheader("Atividade de Anotação")
    # MUDANÇA: Texto atualizado com exemplo
    st.markdown("""
    Agora que você observou os espectros, anote na tabela abaixo os comprimentos de onda (em nm) que você identificou.
    **Preencha cada coluna 'Linha' com um único valor.**

    Use a última coluna para adicionar **comentários e observações** sobre as características das linhas (ex: largas, finas, muito próximas, etc.).
    """)

    # 1. Prepara os dados para a tabela (sem a coluna de dados reais)
    # Tabela interativa usando st.session_state para preservar os dados
    if 'df_atlas_activity' not in st.session_state:
        elementos = list(LINHAS_ATLAS.keys())
        dados_iniciais_e2 = {
            "Elemento": elementos,
            "Linha 1 (nm)": [""] * len(elementos),
            "Linha 2 (nm)": [""] * len(elementos),
            "Linha 3 (nm)": [""] * len(elementos),
            "Linha 4 (nm)": [""] * len(elementos),
            "Linha 5 (nm)": [""] * len(elementos),
            "Observações / Comentários": [""] * len(elementos)
        }
        # 1. CRIA a tabela na memória na primeira vez
        st.session_state.df_atlas_activity = pd.DataFrame(dados_iniciais_e2)

    # 2. LÊ da memória, exibe para edição e adiciona a KEY
    df_editado_e2 = st.data_editor(
        st.session_state.df_atlas_activity,
        num_rows="dynamic",
        hide_index=True,
        key="editor_etapa2"  # <-- Adiciona uma key única e estável
    )

    # 3. SALVA as alterações de volta na memória (passo crucial)
    st.session_state.df_atlas_activity = df_editado_e2

    # Botão de download usando a função universal
    st.divider()

    # Cria a "lista de tarefas" para o relatório
    itens_relatorio_e2 = [
        {
            'tipo': 'tabela',
            'titulo': 'Tabela de Anotações do Atlas Espectral',
            'df': df_editado_e2
        }
    ]

    # Gera o relatório e cria o botão
    relatorio_csv_e2 = gerar_relatorio_universal(itens_relatorio_e2)
    st.download_button(
        label="📥 Baixar Anotações do Atlas (CSV)",
        data=relatorio_csv_e2.encode('utf-8'),
        file_name='anotacoes_atlas_espectral.csv',
        mime='text/csv'
    )

    # O tutorial do CSV pode vir depois, se você o tiver nesta aba
    # mostrar_tutorial_csv()

    mostrar_tutorial_csv()


# --- CÓDIGO DA ETAPA 3 (TRADUÇÃO LITERAL DA CÉLULA 3) ---
with tab3:
    st.header("Modelo simples de espectro de absorção")
    with st.expander("Clique aqui para entender por que os espectros das estrelas têm 'vales'"):
        st.markdown("""
        Na Etapa 1, vimos o espectro **ideal** de uma estrela, a curva suave da radiação de corpo negro. No entanto, quando olhamos para uma estrela real, o espectro que vemos não é assim tão perfeito. Ele é cheio de "vales" ou linhas escuras, como você pode ver no simulador abaixo. Mas o que são esses vales?

        ### Por que o Espectro de uma Estrela não é Ideal?

        Imagine que o núcleo denso de uma estrela produz uma luz intensa e contínua, como uma lâmpada incandescente. Esse seria o espectro de corpo negro perfeito, um arco-íris completo e sem falhas.

        Porém, essa luz precisa atravessar a atmosfera mais externa e mais fria da estrela para chegar até nós. Nessa atmosfera, existem átomos de vários elementos químicos (hidrogênio, hélio, cálcio, etc.). Cada tipo de átomo é "sintonizado" para absorver comprimentos de onda (cores) muito específicos de luz.

        Quando a luz contínua do núcleo passa pela atmosfera, os átomos "roubam" exatamente a energia que eles gostam de absorver. O resultado é que, no espectro que chega à Terra, faltam essas cores específicas. Esses "vales" são as **linhas de absorção**. Eles são as impressões digitais dos elementos presentes na atmosfera da estrela.

        ### As Leis de Kirchhoff e os 3 Tipos de Espectros

        No século XIX, o físico Gustav Kirchhoff formulou três leis que descrevem perfeitamente como esses espectros são formados:
        """)

        col1, col2 = st.columns(2)
        with col1:
            st.image("assets/lei_espectro.jpg", caption="Fonte: Adapatado de https://commons.wikimedia.org/wiki/File:Kirchhoff-spectroscopy-law.svg")
        with col2:
            st.markdown("""
            **1. Espectro Contínuo:**
            - **O que é:** Um espectro completo e ininterrupto.
            - **Como se forma:** É produzido por um objeto denso e quente, como o núcleo de uma estrela ou o filamento de uma lâmpada incandescente. A luz é emitida em todos os comprimentos de onda. **(Lei 1 de Kirchhoff)**

            **2. Espectro de Emissão:**
            - **O que é:** Apenas algumas linhas coloridas brilhantes sobre um fundo preto.
            - **Como se forma:** É produzido por um gás quente de baixa densidade. O gás não emite um espectro contínuo, mas apenas energias (correspondente a comprimento de onda) específicas que seus átomos são capazes de emitir. É o oposto do espectro de absorção. **(Lei 2 de Kirchhoff)**

            **3. Espectro de Absorção:**
            - **O que é:** Um espectro contínuo com linhas escuras (vales).
            - **Como se forma:** É produzido quando a luz de uma fonte quente e contínua passa por um gás mais frio e de baixa densidade (como a atmosfera de uma estrela). O gás frio absorve as mesmas energias que emitiria se estivesse quente. **(Lei 3 de Kirchhoff)**

            - Volte para Etapa 2 e observe o espectro de absorção de alguns elementos químicos.
            """)
        st.success("**Conclusão:** O espectro de uma estrela é um **espectro de absorção** porque estamos vendo a luz contínua do seu núcleo denso depois que ela foi 'filtrada' pela sua atmosfera mais fria.")


    c1, c2 = st.columns(2)
    with c1:
        temp_e3 = st.slider("Temperatura (K)", 2800, 40000, 5800, 200, key="temp_e3")
        log_g_e3 = st.slider("Gravidade (log g)", 1.0, 5.0, 4.5, 0.1, key="logg_e3")
    with c2:
        x_min_e3 = st.slider("Zoom Mín (nm)", 50, 1000, 380, 10, key="zoom_min_e3")
        x_max_e3 = st.slider("Zoom Máx (nm)", 400, 2000, 750, 10, key="zoom_max_e3")

    # Lógica de plotagem da Etapa 3
    wavelengths = np.linspace(x_min_e3, x_max_e3, 4000)
    temperatura = temp_e3
    log_g = log_g_e3
    classe = get_classe_espectral(temperatura)
    fluxo_continuo = planck(wavelengths, temperatura)
    fluxo_final = np.copy(fluxo_continuo)
    largura_base = 0.2 + (log_g - 1.0) * 0.3
    for nome, (pico_t, largura_t, fator_escala) in PARAMETROS_INTENSIDADE_AJUSTADOS.items():
        if nome in LINHAS_QUENTES and temperatura < 7500: continue
        if nome in LINHAS_FRIAS and temperatura > 8000: continue
        if nome == "Fe II" and temperatura < 4000: continue
        intensidade_relativa = np.exp(-((temperatura - pico_t)**2) / (2 * largura_t**2))
        if nome == "H" and temperatura >= 10000: intensidade_relativa = max(intensidade_relativa, 0.15)
        if nome == "TiO": intensidade_relativa = 1 / (1 + np.exp(0.005 * (temperatura - 3600)))
        if intensidade_relativa > 0.05:
            largura_linha = largura_base if nome != "TiO" else 8.0
            for linha_pos in LINHAS_ATLAS[nome]["linhas"]:
                idx_linha = np.argmin(np.abs(wavelengths - linha_pos))
                continuo_na_linha = fluxo_continuo[idx_linha]
                profundidade = (0.95 * intensidade_relativa * fator_escala) * continuo_na_linha
                gaussiana = profundidade * np.exp(-((wavelengths - linha_pos)**2) / (2 * largura_linha**2))
                fluxo_final -= gaussiana
    fluxo_final = np.clip(fluxo_final, 0, None)
    max_visivel = np.max(fluxo_continuo)
    if max_visivel == 0: max_visivel = 1
    continuo_norm = fluxo_continuo / max_visivel
    final_norm = fluxo_final / max_visivel
    pico_wien_nm = calcular_pico_wien(temperatura)
    fig, ax = plt.subplots(figsize=(14, 7))
    fig.set_facecolor('black'); ax.set_facecolor('#1e1e1e')
    ax.plot(wavelengths, continuo_norm, color='dimgray', linestyle=':', lw=1.5, alpha=0.9, label='Corpo Negro Ideal')
    ax.plot(wavelengths, final_norm, color='white', lw=1.5, label='Espectro com Absorção')
    if x_min_e3 <= pico_wien_nm <= x_max_e3:
        ax.axvline(x=pico_wien_nm, color='gold', linestyle='--', linewidth=2, label=f'Pico de Wien: {pico_wien_nm:.1f} nm')
    ax.set_title(f'Espectro Simulado para uma Estrela de {temperatura} K (Classe {classe})', fontsize=16, color='white')
    ax.set_xlabel('Comprimento de Onda (nm)', color='white')
    ax.set_ylabel('Intensidade Relativa', color='white')
    ax.set_xlim(x_min_e3, x_max_e3)
    lim_y = np.max(continuo_norm) * 1.1 if np.max(continuo_norm) > 0 else 1.1
    ax.set_ylim(-0.05, lim_y)
    ax.grid(True, linestyle='--', alpha=0.5, color='gray')
    ax.tick_params(colors='white', which='both')
    ax.legend(loc='best')
    st.pyplot(fig)


# --- CÓDIGO DA ETAPA 4 (TRADUÇÃO LITERAL DA CÉLULA 4) ---
with tab4:
    st.header("Atividade de identificação de átomos e composto em espectro de absorção")

    st.markdown("Use os controles abaixo para gerar espectros de estrelas com diferentes temperaturas. O gráfico de cima mostra a curva de corpo negro e o de baixo mostra as linhas de absorção que apareceriam.")
    c1, c2 = st.columns(2)
    with c1:
        temp_e4 = st.slider("Temperatura (K)", 2800, 40000, 5800, 200, key="temp_e4")
        log_g_e4 = st.slider("Gravidade (log g)", 1.0, 5.0, 2.0, 0.1, key="logg_e4")
    with c2:
        x_min_e4 = st.slider("Zoom Mín (nm)", 100, 1000, 380, 10, key="zoom_min_e4")
        x_max_e4 = st.slider("Zoom Máx (nm)", 400, 2000, 750, 10, key="zoom_max_e4")

    # MUDANÇA 1: Adicionada a explicação sobre log(g)
    with st.expander("O que significa 'Gravidade (log g)'?"):
      st.markdown("""
    O termo **log(g)** refere-se à **gravidade na superfície** da estrela, que está diretamente relacionada à pressão em sua atmosfera.

    * **'g'** é a aceleração da gravidade na superfície. Ela depende tanto da **massa** da estrela quanto do seu **raio**.
    * **'log'** é a escala logarítmica, usada para facilitar o trabalho com a vasta gama de valores de gravidade encontrados no universo.

    A relação chave é: estrelas com **raio pequeno e alta densidade** (como anãs) têm **alta gravidade superficial (log g alto)**. Estrelas com **raio muito grande** (como as gigantes e supergigantes), mesmo que sejam muito massivas, têm uma atmosfera expandida e, portanto, **baixa gravidade superficial (log g baixo)**.

    **Efeito no Espectro:** Uma gravidade maior (log g alto) comprime a atmosfera estelar, causando mais colisões entre os átomos. Essa "pressão" alarga as linhas de absorção. Portanto, estrelas gigantes (log g baixo) têm linhas espectrais finas e nítidas, enquanto estrelas anãs (log g alto) têm linhas mais largas.
    """)
    # Lógica de plotagem da Etapa 4
    wavelengths = np.linspace(x_min_e4, x_max_e4, 4000)
    temperatura = temp_e4
    log_g = log_g_e4
    classe = get_classe_espectral(temperatura)
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10), sharex=True, gridspec_kw={'height_ratios': [1, 1]})
    fig.set_facecolor('black')
    ax1.set_facecolor('#1e1e1e')
    fluxo_continuo = planck(wavelengths, temperatura)
    max_visivel = np.max(fluxo_continuo)
    if max_visivel == 0: max_visivel = 1
    continuo_norm = fluxo_continuo / max_visivel
    pico_nm = calcular_pico_wien(temperatura)
    grad_wl = np.linspace(380, 700, 500)
    grad_img = np.vstack((grad_wl, grad_wl))
    cmap = LinearSegmentedColormap.from_list('vis', [(0.0,(0.29,0,0.51)), (0.17,(0,0,1)), (0.33,(0,1,1)), (0.50,(0,1,0)), (0.67,(1,1,0)), (0.83,(1,0.5,0)), (1.0,(1,0,0))])
    ax1.imshow(grad_img, aspect='auto', cmap=cmap, extent=[380, 700, -0.05, 1.1])
    ax1.plot(wavelengths, continuo_norm, color='white', lw=2)
    if wavelengths.min() <= pico_nm <= wavelengths.max():
        ax1.axvline(x=pico_nm, color='gold', linestyle='--', lw=2, label=f'Pico de Wien: {pico_nm:.1f} nm')
    ax1.set_title(f'1. Espectro de Corpo Negro para {temperatura} K (Classe {classe})', color='white')
    ax1.set_ylabel('Intensidade Relativa', color='white')
    ax1.legend(loc='lower left'); ax1.grid(True, alpha=0.2); ax1.tick_params(colors='white'); ax1.set_ylim(-0.05, 1.1)
    ax2.set_facecolor('#1e1e1e')
    fluxo_absorcao = np.ones_like(wavelengths)
    largura_base = 0.2 + (log_g - 1.0) * 0.3
    for nome, (pico_t, largura_t, fator_escala) in PARAMETROS_INTENSIDADE_AJUSTADOS.items():
        if nome in LINHAS_QUENTES and temperatura < 7500: continue
        if nome in LINHAS_FRIAS and temperatura > 8000: continue
        if nome == "Fe II" and temperatura < 4000: continue
        intensidade_relativa = np.exp(-((temperatura - pico_t)**2) / (2 * largura_t**2))
        if nome == "H" and temperatura >= 10000:
            intensidade_relativa = max(intensidade_relativa, 0.15)
        if nome == "TiO":
            intensidade_relativa = 1 / (1 + np.exp(0.005 * (temperatura - 3600)))
        if intensidade_relativa > 0.05:
            largura_linha = largura_base if nome != "TiO" else 8.0
            for linha_pos in LINHAS_ATLAS[nome]["linhas"]:
                if wavelengths.min() <= linha_pos <= wavelengths.max():
                    profundidade = (1.0 * intensidade_relativa) * fator_escala
                    gaussiana = profundidade * np.exp(-((wavelengths - linha_pos)**2) / (2 * largura_linha**2))
                    fluxo_absorcao -= gaussiana
    ax2.plot(wavelengths, np.clip(fluxo_absorcao, 0, 1), color='white', lw=1.5)
    ax2.set_title(f'2. Linhas de Absorção para log g = {log_g:.1f}', color='white')
    ax2.set_xlabel('Comprimento de Onda (nm)', color='white')
    ax2.set_ylabel('Intensidade Normalizada', color='white')
    ax2.grid(True, alpha=0.2); ax2.tick_params(colors='white'); ax2.set_ylim(-0.05, 1.1)
    st.pyplot(fig)

    # --- INÍCIO DA NOVA SEÇÃO DE ATIVIDADE ---
    st.divider()
    st.header("Missão: Decifrando o espectro na faixa do visível")
    st.info("""
    **Seu objetivo:** Agir como um(a) astrofísico(a) e identificar quais elementos químicos deixam suas "impressões digitais" em estrelas de diferentes temperaturas.

    **Instruções:**
    1.  Use os sliders acima para escolher uma temperatura (ou use as temperaturas que você investigou na Etapa 1 para cada classe espectral).
    2.  Observe atentamente o gráfico normalizado **"2. Linhas de Absorção"**.
    3.  Consulte o **"Etapa 2: Atlas Espectral"** (e seus dados) para comparar as posições dos "vales" (linhas de absorção) com as linhas de referência de cada elemento.
    4.  Preencha a tabela abaixo com suas descobertas. Adicione uma nova linha para cada classe espectral que você analisar.
    """)

    # Tabela interativa para a atividade
    if 'df_identificacao' not in st.session_state:
      dados_iniciais_e4 = {
        "Classe Espectral": ["G (Exemplo)", ""],
        "Temperatura (K)": [5800, None],
        "Elementos Identificados": ["Ca II, H, Fe I", ""],
        "Intensidade (ordem decrescente)": ["Ca II (muito forte), Fe I, H", ""],
        "Observações / Comentários": ["As linhas do Cálcio II são muito proeminentes e ...", ""]
        }
      st.session_state.df_identificacao = pd.DataFrame(dados_iniciais_e4)

    df_editado_e4 = st.data_editor(
        st.session_state.df_identificacao,
        num_rows="dynamic",
        hide_index=True,
        key="editor_etapa4"
    )
    st.session_state.df_identificacao = df_editado_e4

    csv_para_download_e4 = convert_df_to_csv(df_editado_e4)
    st.download_button(label="📥 Baixar tabela de identificação (CSV)", data=csv_para_download_e4, file_name='minha_identificacao_espectral.csv', mime='text/csv')

    # Perguntas de análise
    st.divider()
    st.subheader("Perguntas para Análise")
    st.markdown("1. Quais elementos (ou moléculas, como o TiO) têm suas linhas de absorção mais fortes em estrelas de **baixa temperatura** (ex: ~3.000 K - 4.000 K)?")
    resposta1 = st.text_area("Resposta 1:", height=100, key="r1_e4")

    st.markdown("2. Olhando para todas as suas observações na tabela, qual elemento parece estar presente e visível na **maioria das classes espectrais** que você analisou?")
    resposta2 = st.text_area("Resposta 2:", height=100, key="r2_e4")

    # MUDANÇA 3: Adicionada a nova pergunta sobre log(g)
    st.markdown("3. Mantenha a temperatura fixa (ex: 6000 K) e mova o slider 'Gravidade (log g)'. O que acontece com a **largura** das linhas de absorção quando você aumenta ou diminui o valor de log(g)? Descreva por que a largura das linhas espectrais varia e quais são as diferenças entre as características de estrelas com alto e baixo log(g).")
    resposta3 = st.text_area("Resposta 3:", height=100, key="r3_e4")

    # MUDANÇA 2: Lógica para mostrar o "spoiler" apenas após 6 observações
    st.divider()
    # Conta quantas linhas foram preenchidas na coluna "Elementos Identificados"
    observacoes_feitas = (df_editado_e4['Elementos Identificados'].str.strip() != '').sum()
    reflexao_final = ""
    if observacoes_feitas >= 6:

# NOVA SEÇÃO SOBRE CECILIA PAYNE (baseada no artigo)
        st.subheader("A revolução de uma cientista: Descoberta, Gênero e Poder")
        st.markdown("""
        #### A Crença Antiga: Um Universo com a nossa Cara
        Até a década de 1920, a visão predominante, defendida por gigantes da área como o astrofísico **Henry Norris Russell**, era de que as estrelas e a Terra tinham composições químicas semelhantes. A lógica era simples e baseada em observação direta: como as linhas espectrais de metais como Ferro (Fe) e Cálcio (Ca) eram as mais fortes no espectro do Sol, esses deveriam ser os elementos mais abundantes. Acreditava-se que a intensidade de uma linha era um indicativo direto da quantidade do elemento.

        #### A Tese que mudou tudo
        Em sua tese de doutorado em 1925, **Cecilia Payne** fez algo radical.Usando a recém-desenvolvida teoria quântica, ela construiu um método quantitativo para explicar as linhas espectrais. Sua análise matemática rigorosa a levou a uma conclusão que contrariava todo o conhecimento vigente:

        * **Hidrogênio e Hélio não eram apenas presentes, mas sim os componentes esmagadoramente dominantes do universo**. Em suas contas, o hidrogênio era mais de um milhão de vezes mais abundante que o ferro na atmosfera solar.
        * A intensidade de uma linha espectral **não mede a abundância**, mas sim as **condições físicas** (principalmente a temperatura) da atmosfera da estrela, que determinam se um átomo está no estado correto de excitação para absorver energia.

        **Por que as linhas "mentem"?**
        Para um átomo absorver luz, seu elétron precisa estar em um nível de energia específico para poder "saltar" para um nível mais alto. A temperatura da estrela determina se os elétrons estão nesse estado ideal:

        * **Em estrelas muito frias:** Os átomos não têm energia suficiente para excitar seus elétrons para o nível correto. As linhas de absorção visíveis são fracas ou inexistentes.
        * **Em estrelas muito quentes:** A energia é tão alta que a maioria dos elétrons já foi arrancada dos átomos (ionização). Sobram poucos átomos no estado certo para absorver a radiação.

        #### A inércia do conhecimento: O Confronto com o patriarcado e a autoridade
        A descoberta de Payne foi tão revolucionária que foi recebida com enorme ceticismo. O próprio Russell, que era consultor de sua tese, a aconselhou a **não** publicar sua principal conclusão, escrevendo que era "claramente impossível" que o hidrogênio fosse tão abundante.

        Payne enfrentava um sistema onde a autoridade científica era exclusivamente masculina. Desde seus tempos de estudante em Cambridge, ouviu de um diretor que "jamais seria uma astrônoma" e, em Harvard, mesmo realizando trabalho complexo, este era classificado como de "caráter feminino", com remuneração inferior. Pressionada por uma das figuras mais poderosas da astronomia mundial, ela cedeu e adicionou uma ressalva em sua tese, afirmando que sua descoberta sobre a abundância de hidrogênio e hélio era "quase certamente não real".

        Quatro anos depois, usando uma metodologia diferente, o próprio Henry Norris Russell chegou à mesma conclusão que Payne. Seu artigo se tornou a referência na área, e por muito tempo ele foi creditado como o pioneiro da descoberta. Embora ele tenha citado o trabalho dela, não mencionou que ela havia chegado à resposta correta anos antes e fora dissuadida por ele.

        Cecilia Payne continuou sua carreira em Harvard por mais de trinta anos, mas só foi oficialmente nomeada "professora" em 1956, tornando-se a primeira mulher a chefiar um departamento na universidade. Sua história é um lembrete poderoso de que a ciência não é uma busca puramente objetiva; ela é uma construção humana, influenciada por preconceitos, relações de poder e pela coragem daqueles que ousam desafiar o consenso.
        """)


        st.markdown("---")
        st.caption("""
    **Material de Apoio (Para Alunos e Professores):**

    A história de como Cecilia Payne revolucionou nosso entendimento da composição do universo é fascinante e um marco na ciência. Para saber mais sobre seu trabalho e a física por trás da análise espectral, leia o artigo:

    * [O papel de Cecilia Payne na determinação da composição estelar](https://doi.org/10.1590/1806-9126-RBEF-2021-0028)
    * [Raça, gênero e classe social nas ciências físicas: o silêncio dos homens](https://doi.org/10.47456/Cad.Astro.v5nEspecial.44894)
    """)
        # --- PERGUNTA FINALIZADORA (NOVA SEÇÃO) ---
        st.divider()
        st.header("Reflexão final")
        st.markdown("""
        A trajetória de Cecilia Payne-Gaposchkin é um exemplo poderoso de como a ciência é uma construção humana, sujeita a preconceitos, mas também impulsionada pela coragem de pessoas marginalizadas e silenciadas.

        Com base no que você leu, escreva uma reflexão sobre como os desafios de gênero e a pressão de cientistas estabelecidos impactaram não apenas a carreira de Cecilia, mas também o próprio avanço do conhecimento científico. 
        
        Reunám-se com os seus colegas e discuta os termos "caráter feminino" e "jamais seria uma astrônoma" no contexto do texto. O que esse tipo de atitude impacta na sociedade? Quais vozes/sujeitos estão em posição de poder, e em relação a quem? **
        """)

        reflexao_final = st.text_area("Escreva sua reflexão final aqui:", height=200, key="reflexao_final")

    else:
        st.info(f"""
        Você fez **{observacoes_feitas}** de **6** observações necessárias.

        Continue preenchendo a tabela de identificação para revelar uma conclusão importante sobre a análise espectral!
        """)

# --- NOVO BOTÃO DE DOWNLOAD ÚNICO ---
    st.divider()
    st.header("Salvar seu trabalho")
    st.markdown("Clique no botão abaixo para baixar um relatório completo (.csv) com sua tabela e todas as suas respostas desta etapa.")

    # 1. Crie a "lista de tarefas" para o relatório da Etapa 4
    itens_relatorio_e4 = [
        {
            'tipo': 'tabela',
            'titulo': 'Tabela de Identificação Espectral',
            'df': df_editado_e4
        },
        {
            'tipo': 'qa',
            'pergunta': '1. Elementos mais fortes em estrelas de baixa temperatura?',
            'resposta': resposta1
        },
        {
            'tipo': 'qa',
            'pergunta': '2. Elemento visível na maioria das classes espectrais?',
            'resposta': resposta2
        },
        {
            'tipo': 'qa',
            'pergunta': '3. O que acontece com a largura das linhas ao variar o log(g)?',
            'resposta': resposta3
        }
    ]
    # Adiciona a reflexão final apenas se ela existir
    if reflexao_final:
        itens_relatorio_e4.append({
            'tipo': 'qa',
            'pergunta': 'Reflexão Final sobre Cecilia Payne',
            'resposta': reflexao_final
        })

    # 2. Gere o relatório chamando a função universal
    relatorio_csv = gerar_relatorio_universal(itens_relatorio_e4)

    # 3. Crie o botão de download
    st.download_button(
        label="📥 Baixar relatório completo da etapa 4 (CSV)",
        data=relatorio_csv.encode('utf-8'),
        file_name='relatorio_completo_etapa4.csv',
        mime='text/csv'
    )
    mostrar_tutorial_csv()

# --- CÓDIGO DA ETAPA 5 (TRADUÇÃO LITERAL DA CÉLULA 5) ---
with tab5:
    st.header("Linha de referencia de espectro no visível")

    c1, c2 = st.columns(2)
    with c1:
        temp_e5 = st.slider("Temperatura (K)", 2800, 40000, 5800, 200, key="temp_e5")
        log_g_e5 = st.slider("Gravidade (log g)", 1.0, 5.0, 2.0, 0.1, key="logg_e5")
    with c2:
        x_min_e5 = st.slider("Zoom Mín (nm)", 100, 1000, 380, 10, key="zoom_min_e5")
        x_max_e5 = st.slider("Zoom Máx (nm)", 400, 2000, 750, 10, key="zoom_max_e5")

    st.subheader("Marque os elementos para revelar suas posições:")
    marcadores_selecionados = []
    cols = st.columns(6)
    for i, nome in enumerate(LINHAS_ATLAS.keys()):
        with cols[i % 6]:
            if st.checkbox(nome, key=f"check_e5_{nome}"):
                marcadores_selecionados.append(nome)

    # Lógica de plotagem da Etapa 5
    wavelengths = np.linspace(x_min_e5, x_max_e5, 4000)
    temperatura = temp_e5
    log_g = log_g_e5
    classe = get_classe_espectral(temperatura)
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10), sharex=True, gridspec_kw={'height_ratios': [1, 1]})
    fig.set_facecolor('black')
    ax1.set_facecolor('#1e1e1e')
    fluxo_continuo = planck(wavelengths, temperatura)
    max_visivel = np.max(fluxo_continuo)
    if max_visivel == 0: max_visivel = 1
    continuo_norm = fluxo_continuo / max_visivel
    pico_nm = calcular_pico_wien(temperatura)
    grad_wl = np.linspace(380, 700, 500)
    grad_img = np.vstack((grad_wl, grad_wl))
    cmap = LinearSegmentedColormap.from_list('vis', [(0.0,(0.29,0,0.51)), (0.17,(0,0,1)), (0.33,(0,1,1)), (0.50,(0,1,0)), (0.67,(1,1,0)), (0.83,(1,0.5,0)), (1.0,(1,0,0))])
    ax1.imshow(grad_img, aspect='auto', cmap=cmap, extent=[380, 700, -0.05, 1.1])
    ax1.plot(wavelengths, continuo_norm, color='white', lw=2)
    if wavelengths.min() <= pico_nm <= wavelengths.max():
        ax1.axvline(x=pico_nm, color='gold', linestyle='--', lw=2, label=f'Pico de Wien: {pico_nm:.1f} nm')
    ax1.set_title(f'1. Espectro de Corpo Negro para {temperatura} K (Classe {classe})', color='white')
    ax1.set_ylabel('Intensidade Relativa', color='white')
    ax1.legend(loc='lower left'); ax1.grid(True, alpha=0.2); ax1.tick_params(colors='white'); ax1.set_ylim(-0.05, 1.1)
    ax2.set_facecolor('#1e1e1e')
    fluxo_absorcao = np.ones_like(wavelengths)
    largura_base = 0.2 + (log_g - 1.0) * 0.3
    for nome, (pico_t, largura_t, fator_escala) in PARAMETROS_INTENSIDADE_AJUSTADOS.items():
        if nome in LINHAS_QUENTES and temperatura < 7500: continue
        if nome in LINHAS_FRIAS and temperatura > 8000: continue
        if nome == "Fe II" and temperatura < 4000: continue
        intensidade_relativa = np.exp(-((temperatura - pico_t)**2) / (2 * largura_t**2))
        if nome == "H" and temperatura >= 10000:
            intensidade_relativa = max(intensidade_relativa, 0.15)
        if nome == "TiO":
            intensidade_relativa = 1 / (1 + np.exp(0.005 * (temperatura - 3600)))
        if intensidade_relativa > 0.05:
            largura_linha = largura_base if nome != "TiO" else 8.0
            for linha_pos in LINHAS_ATLAS[nome]["linhas"]:
                if wavelengths.min() <= linha_pos <= wavelengths.max():
                    profundidade = (1.0 * intensidade_relativa) * fator_escala
                    gaussiana = profundidade * np.exp(-((wavelengths - linha_pos)**2) / (2 * largura_linha**2))
                    fluxo_absorcao -= gaussiana
    ax2.plot(wavelengths, np.clip(fluxo_absorcao, 0, 1), color='white', lw=1.5)
    # Lógica para desenhar os marcadores
    for nome, dados in LINHAS_ATLAS.items():
        if nome in marcadores_selecionados:
            for linha_pos in dados["linhas"]:
                if x_min_e5 <= linha_pos <= x_max_e5:
                    ax2.axvline(x=linha_pos, color=dados["cor"], linestyle='--', lw=1.2, alpha=0.9)
    ax2.set_title(f'2. Linhas de Absorção para log g = {log_g:.1f}', color='white')
    ax2.set_xlabel('Comprimento de Onda (nm)', color='white')
    ax2.set_ylabel('Intensidade Normalizada', color='white')
    ax2.grid(True, alpha=0.2); ax2.tick_params(colors='white'); ax2.set_ylim(-0.05, 1.1)
    st.pyplot(fig)

# --- CÓDIGO DA ETAPA 6: ANÁLISE DE ESPECTROS REAIS ---
with tab6:
    st.header("🔭 Etapa 6: Análise de Espectros Reais")

    # TEXTO INTRODUTÓRIO QUE VOCÊ PEDIU
    st.markdown("""
    Bem-vindo(a) à fronteira da astrofísica moderna! Até agora, você trabalhou com um simulador idealizado, um ambiente controlado para aprender os conceitos fundamentais. Agora, vamos encarar o desafio que os astrofísicos enfrentam todos os dias: analisar dados reais.

    Grandes levantamentos de dados, como o **Sloan Digital Sky Survey (SDSS)** e bancos de dados especializados como o **Montreal White Dwarf Database (MWDD)**, coletaram milhões de espectros de estrelas, galáxias e quasares. Este trabalho monumental nos permite entender a evolução do universo, a composição de estrelas distantes e até mesmo os restos de planetas que orbitaram estrelas mortas.

    Ao olhar para os gráficos abaixo, você notará que eles parecem bem mais "desconfortáveis" e caóticos do que os do nosso simulador. Isso porque dados reais contêm **ruído**: flutuações aleatórias causadas pelo detector do telescópio, pela atmosfera da Terra ou por fontes de luz de fundo. Um pequeno "vale" pode ser uma linha de absorção real de um elemento químico ou apenas uma flutuação aleatória do ruído.

    É aqui que entra a experiência do astrofísico: com estudo e técnicas de processamento de dados, ele aprende a diferenciar o sinal do ruído para, com confiança, identificar os elementos que compõem uma estrela.
    """)

    # EXPANDER SOBRE ANGSTROM VS NANÔMETRO
    with st.expander("Clique aqui para entender a unidade de medida Angstrom (Å)"):
        st.markdown(r"""
        Nos gráficos de espectros profissionais, é muito comum encontrar o comprimento de onda medido em **Angstroms (Å)**, em vez de nanômetros (nm). Ambas são unidades de medida de comprimento extremamente pequenas, mas possuem uma relação simples entre si.

        O Angstrom foi nomeado em homenagem ao físico sueco Anders Jonas Ångström e é definido como:
        $1 \text{ Å} = 10^{-10} \text{ metros}$

        A relação com o nanômetro é:
        $$ 1 \text{ nm} = 10 \text{ Å} $$

        **Regra prática:** Para converter de Angstrom (Å) para nanômetro (nm), basta **dividir o valor por 10**.

        **Exemplo:**
        Um comprimento de onda de **4000 Å** (comum no espectro violeta) é equivalente a:
        $$ \frac{4000 \text{ Å}}{10} = 400 \text{ nm} $$
        Este é o mesmo valor que você vê no eixo do nosso simulador.
        """)

    st.divider()
    st.subheader("Analisando os Dados")

    # ABAS INTERNAS PARA CADA ESPECTRO
    spec_tab1, spec_tab2, spec_tab3 = st.tabs(["Espectro 1: Anã Branca", "Espectro 2: Estrela Tipo Solar", "Espectro 3: Super Gigante"])
    with spec_tab1:
        st.subheader("Espectro de uma Estrela Anã Branca (2MASS J00035692-0503328)")

        # Usando colunas para mostrar as duas imagens lado a lado
        col1, col2 = st.columns(2)

        with col1:
            # ATUALIZE O CAMINHO PARA A IMAGEM SEM LINHAS
            st.image("assets/image_35ada1.png", caption="Espectro real de uma anã branca.")
            
        with col2:
            # ATUALIZE O CAMINHO PARA A IMAGEM COM LINHAS
            st.image("assets/image_35ad6a.png", caption="Mesmo espectro, com as linhas de absorção do Hidrogênio identificadas.")

        # Container com a análise profissional que você pediu
        with st.container(border=True):
            st.markdown("""
            #### Análise Profissional: O Fim da Vida de uma Estrela
            
            Este é um espectro real de uma **Anã Branca**, o núcleo denso e quente que resta após uma estrela de massa semelhante à do Sol esgotar seu combustível nuclear e ejetar suas camadas externas. Vamos analisar suas propriedades:

            * **Temperatura Efetiva:** **~17.100 K** (extremamente quente, quase três vezes a temperatura da superfície do Sol, que é ~5.800 K).
            * **Massa:** **0.66 M☉** (cerca de 66% da massa do nosso Sol).
            * **Gravidade Superficial (log g):** **8.07** (o Sol tem um log(g) de ~4.44). Esse valor é **dezenas de milhares de vezes maior** que a gravidade do Sol e indica que a estrela é incrivelmente densa: imagine 66% da massa do Sol espremida em um objeto do tamanho da Terra!

            **Desafio Interativo:** Com uma temperatura de 17.100 K, que cor você esperaria que essa estrela tivesse? Volte para o simulador da **Etapa 1**, ajuste o pico de emissão para corresponder a essa temperatura e compare a cor da curva de corpo negro. A cor branco-azulada que você encontrará lá faz sentido para uma estrela tão quente?

            #### A Importância das "Impressões Digitais"
            
            As duas imagens acima mostram o mesmo espectro. Na segunda, destacamos as "impressões digitais" do átomo de **Hidrogênio** (as linhas da série de Balmer: Hα a 6563 Å, Hβ a 4861 Å, etc.). Reconhecer esses padrões é o primeiro passo para qualquer análise. Uma vez que identificamos com certeza que essas são linhas de hidrogênio, podemos usá-las como **pontos de referência** para estudar outras propriedades da estrela, como a imensa pressão em sua atmosfera (note como as linhas são extremamente largas!).

            #### Reflexão sobre o Desconhecido
            
            Observe o espectro na região **além de 7000 Å**. As linhas de referência mais proeminentes do hidrogênio no visível não estão mais lá, mas o gráfico continua cheio de flutuações. O que você acha que está acontecendo ali? Seriam linhas de outros elementos que não marcamos, ou poderiam ser apenas ruído do detector? É exatamente esse tipo de questão que um astrofísico busca responder.
            """)

        # CAIXA DE TEXTO PARA O ALUNO (ATUALIZADA)
        st.text_area(
            "Analisando as linhas de Hidrogênio (Hα, Hβ, etc.), o que a **largura** delas sugere sobre esta estrela, especialmente quando você se lembra do efeito do log(g) na Etapa 4? E sobre a região após 7000 Å, as flutuações se parecem mais com ruído ou com novas linhas de absorção?",
            height=150,
            key="analise_spec1"
        )
        st.caption("""
        Fonte dos Dados: Os parâmetros da estrela (temperatura, massa, etc.) foram consultados no [Montreal White Dwarf Database (MWDD)](https://www.montrealwhitedwarfdatabase.org/). A imagem do espectro foi gerada a partir dos dados públicos do [Sloan Digital Sky Survey (SDSS)](https://www.sdss.org/).
        """)
    with spec_tab2:
        st.subheader("Espectro de uma Estrela Análoga Solar")

        # ATUALIZE O CAMINHO PARA A NOVA IMAGEM
        st.image("assets/espec_sol.png", caption="Espectro de uma estrela do tipo G, semelhante ao nosso Sol.")

        # Container com a análise profissional
        with st.container(border=True):
            st.markdown("""
            #### Análise Profissional: Encontrando uma Gêmea do Sol?
            
            Este espectro pertence a uma estrela do tipo G, a mesma classe do nosso Sol. À primeira vista, ela parece muito familiar: uma curva suave repleta de linhas de absorção finas, indicando a presença de vários elementos em sua atmosfera.

            Diferente dos espectros normalizados do simulador, este gráfico mostra o fluxo de energia real ($F_{\lambda}$) que recebemos da estrela em unidades físicas. Como ajuda, algumas das linhas de absorção mais importantes já foram identificadas para nós, incluindo as do **Cálcio (CaII)**, **Hidrogênio (Hβ, Hα)** e **Sódio (Na)**.

            #### Um Desafio de Comparação
            
            Nosso Sol tem uma temperatura de superfície de aproximadamente **5777 K** (usaremos esse valor padrão, que é muito próximo do que você usou), e o pico de sua emissão de luz ($\lambda_{max}$) ocorre em torno de **5020 Å (ou 502 nm)**, na cor verde-amarela.

            Agora, observe atentamente o gráfico desta estrela. **Onde você diria que está o pico de emissão dela?** O ponto mais alto da curva parece estar em um comprimento de onda **mais curto** ou **mais longo** que os 5020 Å do Sol?

            **Lembre-se da Lei de Wien da Etapa 1:** estrelas mais quentes têm seu pico de emissão em comprimentos de onda mais curtos (deslocados para o azul). Com base nisso, esta estrela parece ser um pouco mais quente ou um pouco mais fria que o Sol? Sinta-se à vontade para voltar ao simulador e confirmar a relação entre temperatura e pico de emissão!

            #### Explore um Atlas Solar
            
            Para uma comparação detalhada, astrofísicos usam "atlas" espectrais de altíssima resolução do Sol. Se tiver curiosidade, você pode explorar um espectro solar interativo e tentar encontrar as mesmas linhas de absorção no site do : [**BASS2000 Solar Survey**](https://bass2000.obspm.fr/solar_spect.php).
            """)

        # CAIXA DE TEXTO PARA O ALUNO (ATUALIZADA)
        st.text_area(
            "Com base na sua análise visual do pico de emissão, você acha que esta estrela é mais quente ou mais fria que o Sol? Justifique sua resposta usando o que aprendeu na Etapa 1. Além disso, as linhas de CaII e Na estão proeminentes como esperado para uma estrela deste tipo?",
            height=150,
            key="analise_spec2"
        )
        
        # Adicione a fonte dos dados se desejar
        st.caption("""
        Fonte dos Dados: Espectro obtido através dos dados públicos do Sloan Digital Sky Survey (SDSS).
        """)
    with spec_tab3:
        st.subheader("Espectro de uma Estrela Supergigante")

        # ATUALIZE O CAMINHO PARA A IMAGEM DA SUPERGIGANTE
        st.image("assets/super_ging.png", caption="Espectro de uma estrela supergigante do tipo G/K, candidata selecionada do SDSS.")

        # Container com a análise profissional
        with st.container(border=True):
            st.markdown("""
            #### Análise Profissional: O Gigante gentil do cosmos
            #### Parâmetros Físicos da Estrela

            Os dados  do SDSS nos contam a história desta estrela em números. Vamos analisá-los:

            * **Temperatura Efetiva:** **~4.500 K**. Isso confirma que estamos olhando para uma estrela relativamente "fria" (mais fria que o Sol), o que a classifica como uma **Supergigante Vermelha**. Essa temperatura é perfeitamente consistente com o pico de emissão que vemos na região laranja-vermelha do espectro.

            * **Gravidade Superficial (log g):** **~0.9**. Este é um valor extremamente baixo e é a prova numérica do que vimos no espectro. Ele confirma que a atmosfera da estrela é incrivelmente rarefeita e expandida, a característica definitiva de uma supergigante.

            Este é o espectro de uma estrela que selecionamos usando nosso filtro de baixa gravidade superficial (`log(g) < 2`). E o resultado visual é uma confirmação espetacular: estamos olhando para uma **Supergigante Amarela-Laranja**.

            #### A Assinatura de Baixa Gravidade
            
            A característica mais importante e reveladora aqui são as **linhas de absorção**. Observe como as linhas do Hidrogênio (Hβ, Hα), Sódio (Na) e o proeminente trio de linhas do Cálcio (CaII), perto de 8665 Å, são **extremamente finas e bem definidas**.

            **Compare agora:**
            - **Anã Branca (Aba 1):** Linhas imensamente largas devido à pressão atmosférica esmagadora (alto `log(g)`).
            - **Supergigante (Aqui):** Linhas muito estreitas devido a uma atmosfera rarefeita e "fofa" (baixo `log(g)`).

            Essa "magreza" das linhas é a assinatura visual inconfundível de uma estrela de baixíssima densidade.

            #### Temperatura e Evolução
            
            Analisando a forma geral do gráfico, vemos que o pico de emissão de luz ($\lambda_{max}$) desta estrela está em torno de **~6500 Å**, na região amarela-laranja. Isso indica uma temperatura de superfície mais fria que a do Sol (provavelmente abaixo de 5.000 K).
            
            Apesar de ser mais "fria" que o Sol, não se engane. O tamanho colossal desta estrela faz com que ela seja dezenas de milhares de vezes **mais luminosa** no total. Ela está em um estágio avançado de sua vida, já tendo consumido o hidrogênio de seu núcleo e agora "queimando" elementos mais pesados.
            """)

        # CAIXA DE TEXTO PARA O ALUNO (ATUALIZADA)
        st.text_area(
            "Qual é a principal diferença que você nota nas linhas de absorção desta estrela em comparação com a Anã Branca (Aba 1)? O que essa característica nos diz sobre a gravidade e a densidade da atmosfera da supergigante? (Dica: lembre-se do slider `log(g)` da Etapa 4).",
            height=150,
            key="analise_spec3"
        )
        
        # Adicione a fonte dos dados
        st.caption("""
        Fonte dos Dados: Espectro de uma candidata a supergigante, selecionado a partir dos dados públicos do Sloan Digital Sky Survey (SDSS).
        """)
    # --- SEÇÃO DE DOWNLOAD DA ETAPA 6 ---
    st.divider()
    st.header("Salvar seu trabalho da etapa 6")
    st.markdown("Clique no botão abaixo para baixar um relatório completo (.csv) com todas as suas análises dos espectros reais.")

    # 1. Coleta as respostas das caixas de texto
    # O Streamlit guarda o conteúdo dos widgets na session_state usando a 'key' que definimos
    resposta_spec1 = st.session_state.get('analise_spec1', '') # Usar .get para segurança
    resposta_spec2 = st.session_state.get('analise_spec2', '')
    resposta_spec3 = st.session_state.get('analise_spec3', '')

    # 2. Crie a "lista de tarefas" para o relatório da Etapa 6
    itens_relatorio_e6 = [
        {
            'tipo': 'qa',
            'pergunta': 'Análise do Espectro 1 (Anã Branca)',
            'resposta': resposta_spec1
        },
        {
            'tipo': 'qa',
            'pergunta': 'Análise do Espectro 2 (Análoga Solar)',
            'resposta': resposta_spec2
        },
        {
            'tipo': 'qa',
            'pergunta': 'Análise do Espectro 3 (Supergigante)',
            'resposta': resposta_spec3
        }
    ]

    # 3. Gere o relatório chamando a função universal
    relatorio_csv_e6 = gerar_relatorio_universal(itens_relatorio_e6)

    # 4. Crie o botão de download
    st.download_button(
        label="📥 Baixar Análises dos Espectros Reais (CSV)",
        data=relatorio_csv_e6.encode('utf-8'),
        file_name='relatorio_espectros_reais.csv',
        mime='text/csv'
    )

    # 5. Mostra o tutorial de como abrir o arquivo
    mostrar_tutorial_csv()

# --- CÓDIGO DA ETAPA 7: TUTORIAL, REFERÊNCIAS E CRÉDITOS ---
with tab7:
    st.header("🎓 Tutorial: Explorando o Universo com SDSS SQL Search")
    st.markdown("""
    Este tutorial ensina como usar a ferramenta "SQL Search" do Sloan Digital Sky Survey (SDSS) para encontrar tipos específicos de estrelas, como anãs brancas, gigantes, supergigantes e estrelas da sequência principal (como o Sol).
    """)

    st.subheader("Parte 1: Acessando a Ferramenta de Pesquisa SQL")
    st.markdown("""
    Primeiro, precisamos chegar à ferramenta correta no site.
    1. Acesse a página inicial do SDSS SkyServer: [https://skyserver.sdss.org/](https://skyserver.sdss.org/)
    2. No menu superior, clique em **Search Tools**.
    3. No menu que aparece, clique em **SQL Search**.
    
    Você verá uma página com uma grande caixa de texto. É aqui que inserimos nossos comandos.
    """)

    st.subheader("Parte 2: Entendendo o Comando SQL Base")
    st.markdown("""
    Todos os nossos comandos terão uma estrutura parecida. Vamos usar nosso comando de "gêmea solar" como o modelo base para entender cada parte:
    """)
    st.code("""
SELECT TOP 10
    s.specobjid, s.subclass, p.LOGGADOP, p.FEHADOP
FROM
    specObj AS s
JOIN
    SppParams AS p ON s.specobjid = p.SPECOBJID
WHERE
    s.class = 'STAR'
    AND s.subclass LIKE 'G2%'
    AND p.LOGGADOP BETWEEN 4.0 AND 4.5
    AND p.FEHADOP BETWEEN -0.2 AND 0.2
    """, language='sql')
    st.markdown("""
    - **`SELECT TOP 10 ...`**: Diz ao banco de dados o que queremos ver. Estamos pedindo para mostrar o ID do espectro (`specobjid`), a subclasse (`subclass`), a gravidade (`LOGGADOP`) e a metalicidade (`FEHADOP`) dos 10 primeiros resultados que encontrar.
    - **`FROM specObj AS s JOIN SppParams AS p ...`**: Diz onde vamos procurar. Estamos combinando (`JOIN`) duas tabelas: `specObj` (que tem informações básicas do espectro) e `SppParams` (que tem os parâmetros físicos detalhados).
    - **`WHERE ...`**: Esta é a parte mais importante, onde definimos as regras do nosso filtro para encontrar exatamente o que queremos.
    """)

    st.subheader("Parte 3: Como Modificar o Filtro")
    st.markdown("""
    Para encontrar diferentes tipos de estrelas, você só precisa modificar as linhas dentro da cláusula `WHERE`. Os dois parâmetros mais poderosos para isso são `subclass` e `LOGGADOP`.
    """)
    st.info("""
    **1. O Parâmetro `subclass` (O Tipo Espectral)**
    
    - **O que significa?**: A classificação detalhada da estrela baseada na sua temperatura. A sequência é O-B-A-F-G-K-M (da mais quente para a mais fria).
    - **Como modificar?**: Mude `s.subclass LIKE 'G2%'` para:
        - `s.subclass LIKE 'A%'`: Estrelas brancas, como Vega.
        - `s.subclass LIKE 'M%'`: Anãs vermelhas.
        - `s.subclass LIKE 'DA%'`: Anãs brancas com atmosfera de hidrogênio.
    
    *(O símbolo `%` é um curinga que significa "qualquer coisa". Então, `G2%` encontra G2, G2V, etc.)*
    """, icon="🌡️")
    st.info("""
    **2. O Parâmetro `LOGGADOP` (O Tamanho e Tipo da Estrela)**
    
    - **O que significa?**: O logaritmo da gravidade na superfície, um número que nos diz se a estrela é uma anã, gigante ou supergigante.
        - **Valor ALTO (`> 7.0`)**: Gravidade altíssima. Objeto denso e compacto (Anãs Brancas).
        - **Valor MÉDIO (`~4.0` a `4.5`)**: Gravidade "normal" (Sequência Principal, como o Sol).
        - **Valor BAIXO (`~1.0` a `3.5`)**: Gravidade baixa. Estrela grande e "inchada" (Gigantes).
        - **Valor MUITO BAIXO (`< 2.0`)**: Gravidade extremamente baixa. Estrela imensa (Supergigantes).
    - **Como modificar?**: Mude `p.LOGGADOP BETWEEN 4.0 AND 4.5` para:
        - `p.LOGGADOP > 7.0`: Para anãs brancas.
        - `p.LOGGADOP BETWEEN 1.0 AND 3.5`: Para gigantes.
        - `p.LOGGADOP BETWEEN -0.5 AND 2.0`: Para supergigantes.
    """, icon="📏")

    st.subheader("Parte 4: Comandos Prontos para Usar")
    st.markdown("Aqui estão os quatro comandos que desenvolvemos, prontos para copiar e colar.")
    
    with st.expander("Clique para ver os comandos SQL"):
        st.markdown("**1. Estrela de Sequência Principal (Tipo Solar)**")
        st.code("SELECT TOP 10 s.specobjid, s.subclass, p.LOGGADOP, p.FEHADOP FROM specObj AS s JOIN SppParams AS p ON s.specobjid = p.SPECOBJID WHERE s.class = 'STAR' AND s.subclass LIKE 'G2%' AND p.LOGGADOP BETWEEN 4.0 AND 4.5 AND p.FEHADOP BETWEEN -0.2 AND 0.2", language='sql')
        
        st.markdown("**2. Estrela Gigante**")
        st.code("SELECT TOP 10 s.specobjid, s.subclass, p.LOGGADOP FROM specObj AS s JOIN SppParams AS p ON s.specobjid = p.SPECOBJID WHERE s.class = 'STAR' AND p.LOGGADOP BETWEEN 1.0 AND 3.5", language='sql')

        st.markdown("**3. Estrela Supergigante**")
        st.code("SELECT TOP 10 s.specobjid, s.subclass, p.LOGGADOP FROM specObj AS s JOIN SppParams AS p ON s.specobjid = p.SPECOBJID WHERE s.class = 'STAR' AND p.LOGGADOP BETWEEN -0.5 AND 2.0", language='sql')

        st.markdown("**4. Anã Branca**")
        st.code("SELECT TOP 10 s.specobjid, s.subclass, p.LOGGADOP FROM specObj AS s JOIN SppParams AS p ON s.specobjid = p.SPECOBJID WHERE s.class = 'STAR' AND p.LOGGADOP > 7.0", language='sql')

    st.subheader("Parte 5: O Processo Completo")
    st.markdown("""
    1. Navegue até a ferramenta **SQL Search**.
    2. Escolha e copie um dos comandos acima.
    3. Apague o comando que existente e cole o comando que você criou na caixa de texto do site e clique em **Submit**.
    4. Na tabela de resultados, copie um dos números da coluna `specobjid`.
    5. Volte à página inicial do SDSS e clique na ferramenta **Explore**.
    6. Acesse `Search by...` e cole o `specobjid` no campo apropriado (SpecObjID, apstar_id or apogee_id) para ver o espectro e todos os dados da estrela. O espectro interativo geralmente está na seção "Optical Spectra".
    
    Parabéns! Agora você sabe como usar uma ferramenta de pesquisa profissional para explorar um dos maiores catálogos de espectros do mundo.
    """)

    st.divider()

    st.header("📚 Referências Bibliográficas")
    st.markdown("""
    - O papel de Cecilia Payne na determinação da composição estelar: [https://doi.org/10.1590/1806-9126-RBEF-2021-0028](https://doi.org/10.1590/1806-9126-RBEF-2021-0028)
    - Raça, gênero e classe social nas ciências físicas: o silêncio dos homens: [https://doi.org/10.47456/Cad.Astro.v5nEspecial.44894](https://doi.org/10.47456/Cad.Astro.v5nEspecial.44894)
    - DE SOUZA OLIVEIRA FILHO, Kepler; SARAIVA, Maria de Fátima Oliveira. **Astronomia e astrofísica**. Livraria da Física, Rio Grande do Sul, 2004.
    """)

    st.divider()

    st.header("🙏 Agradecimentos")
    st.markdown("""
    Agradecimento especial à **Larissa Luciano Amorim**, doutoranda em astrofísica, pela valiosa colaboração nas aulas de astrofísica.
    *Currículo Lattes: [http://lattes.cnpq.br/2024867681340986](http://lattes.cnpq.br/2024867681340986)*
    """)

    with st.expander("Agradecimento o uso de Dados do SDSS-V"):
        st.caption("""
        O financiamento para o Sloan Digital Sky Survey V foi fornecido pela Fundação Alfred P. Sloan, pela Fundação Heising-Simons, pela Fundação Nacional de Ciência dos EUA (NSF) e pelas instituições participantes. O SDSS reconhece o apoio e os recursos do Centro de Computação de Alto Desempenho da Universidade de Utah. Os telescópios do SDSS estão localizados no Observatório Apache Point, financiado pelo Consórcio de Pesquisa Astrofísica e operado pela Universidade Estadual do Novo México, e no Observatório Las Campanas, operado pela Instituição Carnegie para a Ciência. O site do SDSS é www.sdss.org.
        
        O SDSS é gerenciado pelo Consórcio de Pesquisa Astrofísica para as instituições participantes da colaboração SDSS, incluindo: Instituição Carnegie para a Ciência, Comitê Chileno de Alocação de Tempo (CNTAC), Caltech, Grupo de Participação Gotham, Universidade Harvard, Universidade de Heidelberg, Instituto Flatiron, Universidade Johns Hopkins, Escola Politécnica Federal de Lausanne (EPFL), Instituto Leibniz de Astrofísica de Potsdam (AIP), Instituto Max Planck de Astronomia (MPIA Heidelberg), Instituto Max Planck de Física Extraterrestre (MPE), Universidade de Nanjing, Observatórios Astronômicos Nacionais da China (NAOC), Universidade Estadual do Novo México, Universidade Estadual de Ohio, Universidade Estadual da Pensilvânia, Observatório Astrofísico Smithsonian, Instituto de Ciência do Telescópio Espacial (STScI), Grupo de Participação em Astrofísica Estelar, Universidade Nacional Autônoma do México (UNAM), Universidade do Arizona, Universidade do Colorado Boulder, Universidade de Illinois em Urbana-Champaign, Universidade de Toronto, Universidade de Utah, Universidade da Virgínia, Universidade Yale e Universidade de Yunnan.
        """)